name: My Workflow File
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: My Build
    
    steps:
    - name: Print a greeting
      run:
        echo "Helloo there"

    - name: Checkout my code
      uses: action/checkout@v4
    - name: print content
      run: 
        ls
        
