name: My Second Workflow
on:
  pull_request:
    branches: [main]

jobs:
  builds2:
    runs-on: ubuntu-latest
    name: My Build
    
    steps:
    - name: Print a greeting
      run:
        echo "Helloo there"

    - name: Checkout my code
      uses: actions/checkout@v4
    - name: print content
      run: 
        ls

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Check version of Python
      run: 
        python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest-cov

    - name: begin test
      run: |
        pytest -v -cov --junitxml=report.xml

    # access the hidden repo
    - name: Checkout private repo remotely
      uses: actions/checkout@v4
      with:
        repository: bbgumsab/UOBHidden
        path: hiddenfolder
        token: ${{ secrets.SECRETUOB }}

    - name: Print out the hidden file 
      run: |
        ls
        cd hiddenfolder
        ls
        cat demo.txt

    
